### ISSUE TITLE
python command.py -m web -c data/web.json 失败

### ISSUE THREAD

**Issue by leoxu8703** [CreditEaseDBA/Themis#13]
Traceback (most recent call last):
  File "command.py", line 266, in <module>
    com = Command()
  File "command.py", line 46, in __init__
    settings.MONGO_PASSWORD)
  File "/home/themis-test/Themis-master/rule_analysis/db/mongo_operat.py", line 19, in __init__
    self.conn.admin.authenticate(account, password)
  File "/tmp/.pyenv/versions/2.7.13/envs/env2713/lib/python2.7/site-packages/pymongo/database.py", line 1023, in authenticate
    connect=True)
  File "/tmp/.pyenv/versions/2.7.13/envs/env2713/lib/python2.7/site-packages/pymongo/mongo_client.py", line 423, in _cache_credentials
    sock_info.authenticate(credentials)
  File "/tmp/.pyenv/versions/2.7.13/envs/env2713/lib/python2.7/site-packages/pymongo/pool.py", line 317, in authenticate
    auth.authenticate(credentials, self)
  File "/tmp/.pyenv/versions/2.7.13/envs/env2713/lib/python2.7/site-packages/pymongo/auth.py", line 436, in authenticate
    auth_func(credentials, sock_info)
  File "/tmp/.pyenv/versions/2.7.13/envs/env2713/lib/python2.7/site-packages/pymongo/auth.py", line 416, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info)
  File "/tmp/.pyenv/versions/2.7.13/envs/env2713/lib/python2.7/site-packages/pymongo/auth.py", line 188, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "/tmp/.pyenv/versions/2.7.13/envs/env2713/lib/python2.7/site-packages/pymongo/pool.py", line 213, in command
    read_concern)
  File "/tmp/.pyenv/versions/2.7.13/envs/env2713/lib/python2.7/site-packages/pymongo/network.py", line 101, in command
    helpers._check_command_response(response_doc, msg, allowable_errors)
  File "/tmp/.pyenv/versions/2.7.13/envs/env2713/lib/python2.7/site-packages/pymongo/helpers.py", line 196, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: command SON([('saslStart', 1), ('mechanism', 'SCRAM-SHA-1'), ('payload', Binary('n,,n=sqlreview,r=OTY3Mzc4MjE1MzIy', 0)), ('autoAuthorize', 1)]) on namespace admin.$cmd failed: Authentication failed.
(env2713) [root@pfdqs01 Themis-master]#

**Comment by tuteng** [comment]
这个应该是mongodb 的相关权限没有设置好
