### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'readline'

### ISSUE THREAD

**Issue by bqwzhl20** [CreditEaseDBA/Themis#18]
程序启动几十分钟后就报如下错误了，themis-export进程也就自动退出了。

[2017-11-30 10:39:50,655: ERROR/MainProcess] Control command error: ConnectionError()
Traceback (most recent call last):
    self.node.handle_message(body, message)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/pidbox.py", line 133, in handle_message
    return self.dispatch(**kwdict(body))
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/pidbox.py", line 116, in dispatch
    ticket=ticket)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/pidbox.py", line 139, in reply
    serializer=self.mailbox.serializer)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/pidbox.py", line 245, in _publish_reply
    **opts
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/messaging.py", line 188, in _publish
    mandatory=mandatory, immediate=immediate,
    message, exchange, routing_key, **kwargs
    for queue in _lookup(exchange, routing_key):
    self.get_table(exchange),
    values = client.smembers(key)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/redis/client.py", line 1515, in smembers
    return self.execute_command('SMEMBERS', name)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/redis/client.py", line 567, in execute_command
    connection.disconnect()
    channel._on_connection_disconnect(self)
    raise get_redis_ConnectionError()
ConnectionError
Traceback (most recent call last):
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
[2017-11-30 09:44:01,760: INFO/MainProcess] mingle: searching for neighbors
[2017-11-30 10:39:50,655: ERROR/MainProcess] Control command error: ConnectionError()
Traceback (most recent call last):
    self.node.handle_message(body, message)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/pidbox.py", line 133, in handle_message
    return self.dispatch(**kwdict(body))
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/pidbox.py", line 116, in dispatch
    ticket=ticket)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/pidbox.py", line 139, in reply
    serializer=self.mailbox.serializer)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/pidbox.py", line 245, in _publish_reply
    **opts
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/messaging.py", line 188, in _publish
    mandatory=mandatory, immediate=immediate,
    message, exchange, routing_key, **kwargs
    for queue in _lookup(exchange, routing_key):
    self.get_table(exchange),
    values = client.smembers(key)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/redis/client.py", line 1515, in smembers
    return self.execute_command('SMEMBERS', name)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/redis/client.py", line 567, in execute_command
    connection.disconnect()
    channel._on_connection_disconnect(self)
    raise get_redis_ConnectionError()
ConnectionError
Traceback (most recent call last):
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/home/themis-test/python-project/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/transport/redis.py", line 965, in on_read
able
    item = self.cycle.on_readable(fileno)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/transport/redis.py", line 331, in on_read
able
    return chan.handlers[type]()
  File "/home/themis-test/python-project/lib/python2.7/site-packages/kombu/transport/redis.py", line 598, in _receiv
e
    response = c.parse_response()
  File "/home/themis-test/python-project/lib/python2.7/site-packages/redis/client.py", line 2150, in parse_response
    return self._execute(connection, connection.read_response)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/redis/client.py", line 2132, in _execute
    return command(*args)
  File "/home/themis-test/python-project/lib/python2.7/site-packages/redis/connection.py", line 569, in read_respons
e
    response = self._parser.read_response()
  File "/home/themis-test/python-project/lib/python2.7/site-packages/redis/connection.py", line 224, in read_respons
e
    response = self._buffer.readline()
AttributeError: 'NoneType' object has no attribute 'readline'

**Comment by tuteng** [comment]
看一下你的redis是否正在运行，密码配置是否正确
参考一下这里：https://github.com/celery/kombu/issues/284

**Comment by bqwzhl20** [comment]
配置检查过没有啥问题，redis也正常，这个问题到没有啥影响，审核工具也不是实时运行的，重启就好了
